sudo: required
services:
  - docker

before_install:
  - docker build -t stephanonline/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true stephanonline/docker-react npm run test

language: generic